Ensure that Almanac devices are registered before daemons are running
We need to ensure that we register an Almanc device before starting the `phd` service.

```
EXCEPTION: (PhutilProxyException) Error while executing Task ID 28476658. {>} (PhutilAggregateException) Unable to read device public key while attempting to make authenticated method call within the Phabricator cluster. Use `bin/almanac register` to register keys for this device. Exception: File system entity '/usr/local/src/phabricator/conf/keys/device.pub' does not exist.
  - FilesystemException: File system entity '/usr/local/src/phabricator/conf/keys/device.pub' does not exist. at [<phabricator>/src/applications/repository/storage/PhabricatorRepository.php:2062]
```